name: c3kit_apron_dart
description: A sample command-line application.
version: 1.2.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  intl: ^0.20.2
  sprintf: ^7.0.0
  transit_cljd:
    git:
      url: https://github.com/wevre/transit-cljd
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
